[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mamushi>=0.0.8",
    "ruff>=0.12.12",
    "titanoboa>=0.2.7",
    "vyper>=0.4.3",
]
